#include "Asset/AssetRegistry.h"
#include "Asset/DependencyGraph.h"
#include "Asset/ImportPipeline.h"
#include "Asset/ThumbnailService.h"
#include "Core/EditorApp.h"
#include "Core/EditorCommandBus.h"
#include "Core/EditorSession.h"
#include "Core/EditorState.h"
#include "Core/EditorStateStore.h"
#include "Core/EditorWorkspace.h"
#include "Core/LayoutService.h"
#include "Core/SelectionManager.h"
#include "Core/TransactionSystem.h"
#include "Debug/LogPanel.h"
#include "Debug/MemoryPanel.h"
#include "Debug/ProfilerPanel.h"
#include "Gizmo/TransformGizmo.h"
#include "Panels/ContentBrowserPanel.h"
#include "Panels/DetailsPanel.h"
#include "Panels/IEditorPanel.h"
#include "Panels/ModesPanel.h"
#include "Panels/OutlinerPanel.h"
#include "Panels/OutputLogPanel.h"
#include "Panels/ProjectSettingsPanel.h"
#include "Panels/ToolbarPanel.h"
#include "Panels/ViewportPanel.h"
#include "Plugin/CommandRegistry.h"
#include "Plugin/EditorModuleManager.h"
#include "Plugin/EditorPanelRegistry.h"
#include "Plugin/EditorToolRegistry.h"
#include "Plugin/IEditorModule.h"
#include "Plugin/InspectorWidgetRegistry.h"
#include "Plugin/ShortcutMap.h"
#include "Tools/IEditorTool.h"
#include "Tools/MoveTool.h"
#include "Tools/RotateTool.h"
#include "Tools/ScaleTool.h"
#include "Tools/SelectionTool.h"

namespace rex::editor {
namespace {
void editorSkeletonKeepAlive() {}
}
}

